### ISSUE TITLE
Scribd Endpoint Issue

### ISSUE THREAD

**Issue by muhammadluttfy** [muhammadrafihq/api-issues#2]
halo mas, sebelumnya saya mengucapkan terima kasih untuk public API (Mr APIs) yg di share di group FB Community hehe
izin bantu report issue mas, kyaknya endpoint scribd downloader ada issue ketika digunakan
thankyou mas,...

**Comment by muhammadrafihq** [comment]
Halo mas,
Boleh di infokan untuk error nya seperti apa, karena setelah saya coba barusan status ok
<img width="1375" alt="Screenshot 2024-10-15 at 11 18 53" src="https://github.com/user-attachments/assets/116d587e-743d-4935-942a-58bee72c65bf">


Terimakasih ya sebelumnya.

**Comment by muhammadluttfy** [comment]
oalah iya sekarng sudah bisa mas wkw
saya lupa detail issue nya seperti apa, semalem iseng iseng nyoba dan ada error (ada pesan disuruh report issue kalo gasalah), makanya nyoba report

terima kasih banyak mas
